apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /hello1
        pathType: Prefix
        backend:
          service:
            name: hello1-app-service
            port:
              number: 5000
      - path: /hello2
        pathType: Prefix
        backend:
          service:
            name: hello2-app-service
            port:
              number: 5000