apiVersion: v1
kind: Service
metadata:
  name: hello2-app-service
  namespace: hello
spec:
  selector:
    app: hello2-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8000
#    nodePort: 30001
