apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-hello2-deployment
  namespace: hello
spec:
  selector:
    matchLabels:
      app: redis-hello2
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis-hello2
    spec:
      containers:
      - name: redis-hello2
        image: "docker.io/redis:6.0.5"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
  type: ClusterIP