apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2-app-deployment
  namespace: hello
  labels:
    app: hello2-app
    redis: hello1-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello2-app
  template:
    metadata:
      labels:
        app: hello2-app 
    spec:
      containers:
      - name: hello2-app
        image: localhost:32000/hello-2:latest
        ports:
        - containerPort: 8000
        env:
        - name: host
          value: hello2-app-service
        - name: port
          vaule: 6379
        - name: password
          value: 

