apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1-app-deployment
  namespace: hello
  labels:
    app: hello1-app
    app: hello1-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello1-app
  template:
    metadata:
      labels:
        app: hello1-app 
    spec:
      containers:
      - name: hello1-app
        image: localhost:32000/hello1:latest
        ports:
        - containerPort: 8000
        env:

