apiVersion: v1
kind: Service
metadata:
  name: hello1-app-service
  namespace: hello
spec:
  selector:
    app: hello1-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8000
    nodePort: 30001
