apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1-app-deployment
  namespace: hello
  labels:
    app: hello1-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello1-app
  template:
    metadata:
      labels:
        app: hello1-app 
    spec:
      containers:
      - name: hello1-app
        image: localhost:32000/hello1:latest
        ports:
        - containerPort: 8000
        env:
        - name: host
          value: "hello1-app-service"
        - name: port
          value: "6379"
        - name: password
          value: ""
        readinessProbe:
          httpGet:
            path: /health
            port: 8000