apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1-redis
  namespace: hello
spec:
  selector:
    matchLabels:
      app: redis-hello1
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis-hello1
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
