apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1-redis
spec:
  selector:
    matchLabels:
      app: hello1-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  hello1-app
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
