apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-hello1-deployment
  namespace: hello
spec:
  selector:
    matchLabels:
      app: redis-hello1
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis-hello1
    spec:
      containers:
      - name: redis-hello1
        image: "docker.io/redis:6.0.5"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379